name: Release 6.3 Toolchains
### IMPORTANT NOTE: Copying this workflow for a new release?
# Make sure to run scripts/python/cirun_roll_release.py <release_version> to update the .cirun.yml file!
# Then, replace the runner names with the new ones.

on:
  workflow_dispatch:
  # Schedule to build a new release toolchain weekly on Sunday.
  schedule:
    - cron: "0 20 * * *"

jobs:
  # Each job builds a release toolchain for a specific Swift version.
  build-release-6_3:
    # Note: GitHub requires the use of an 'owner/repo' path before the
    # workflow file path when we want to use a workflow from another branch.
    uses: thebrowsercompany/swift-build/.github/workflows/build-toolchain.yml@release/6.3
    with:
      windows_build_arch: amd64
      windows_x64_default_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-x64-16-2025-11-21--{0}', github.run_id) || 'swift-build-windows-latest-8-cores' }}
      windows_x64_compilers_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-x64-64-2025-11-21--{0}', github.run_id) || 'swift-build-windows-latest-64-cores' }}
      windows_arm64_default_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-arm64-16-2025-11-21--{0}', github.run_id) || 'swift-build-windows-arm64-latest-8-cores' }}
      windows_arm64_compilers_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-arm64-64-2025-11-21--{0}', github.run_id) || 'swift-build-windows-arm64-latest-32-cores' }}
      android_api_level: 28
      build_android: true
    secrets: inherit
    permissions:
      attestations: write
      contents: write
      packages: write
      id-token: write
