name: Schedule - Main Branch Toolchains - Clang

on:
  workflow_dispatch:
  # Schedule to build a new toolchain nightly.
  schedule:
    - cron: "0 1 * * *"

jobs:

  build-release-clang:
    uses: ./.github/workflows/build-toolchain.yml
    with:
      windows_build_arch: amd64
      windows_x64_default_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-x64-16--{0}', github.run_id) || 'swift-build-windows-latest-8-cores' }}
      windows_x64_compilers_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-x64-64--{0}', github.run_id) || 'swift-build-windows-latest-64-cores' }}
      windows_arm64_default_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-arm64-16--{0}', github.run_id) || 'swift-build-windows-arm64-latest-8-cores' }}
      windows_arm64_compilers_runner: ${{ vars.USE_CIRUN == 'true' && format('cirun-win11-pro-arm64-64--{0}', github.run_id) || 'swift-build-windows-arm64-latest-32-cores' }}
      android_api_level: 28
      build_android: true
      use_host_toolchain: false
      create_release: false
      create_snapshot: false
    secrets:
      SYMBOL_SERVER_PAT: ${{ secrets.SYMBOL_SERVER_PAT }}
      CERTIFICATE: ${{ secrets.CERTIFICATE }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      SWIFT_TOOLCHAIN_UPLOADER_ROLE_ARN: ${{ secrets.SWIFT_TOOLCHAIN_UPLOADER_ROLE_ARN }}
      AZURE_SP_CREDENTIALS: ${{ secrets.AZURE_SP_CREDENTIALS }}
      TRUSTED_SIGNING_ACCOUNT: ${{ secrets.TRUSTED_SIGNING_ACCOUNT }}
      TRUSTED_SIGNING_TEST_PROFILE: ${{ secrets.TRUSTED_SIGNING_TEST_PROFILE }}
      TRUSTED_SIGNING_PROD_PROFILE: ${{ secrets.TRUSTED_SIGNING_PROD_PROFILE }}
