name: swift-argument-parser

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'revision to build'
        required: true
        default: 'refs/heads/main'

jobs:
  windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        include:
          - tag: 5.5-DEVELOPMENT-SNAPSHOT-2021-06-02-a
            branch: swift-5.5-branch

    steps:
      - uses: actions/checkout@v2
        with:
          repository: apple/swift-argument-parser
          ref: ${{ inputs.ref }}

      - name: Install Swift ${{ matrix.tag }}
        run: |
          function Update-EnvironmentVariables {
            foreach ($level in "Machine", "User") {
              [Environment]::GetEnvironmentVariables($level).GetEnumerator() | % {
                # For Path variables, append the new values, if they're not already in there
                if ($_.Name -Match 'Path$') {
                  $_.Value = ($((Get-Content "Env:$($_.Name)") + ";$($_.Value)") -Split ';' | Select -Unique) -Join ';'
                }
                $_
              } | Set-Content -Path { "Env:$($_.Name)" }
            }
          }

          Install-Binary -Url "https://swift.org/builds/${{ matrix.branch }}/windows10/swift-${{ matrix.tag }}/swift-${{ matrix.tag }}-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
          Update-EnvironmentVariables

          # Reset Path and environment
          echo "$env:Path" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          Get-ChildItem Env: | % { echo "$($_.Name)=$($_.Value)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append }

      - name: build
        run: |
          swift build -c release

      - name: test
        run: |
          swift test -c release --enable-test-discovery
